// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkarrjvddrdgepbahyrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprYXJyanZkZHJkZ2VwYmFoeXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzIzMjYsImV4cCI6MjA2MDIwODMyNn0.bZd0t1z734lii3fSJjUVbfLvSmKLRZ5ahooBiUZ9O3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);